version: '3'

services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:3.2.1-hadoop3.2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./hadoop.env
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    working_dir: /app

  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./hadoop.env
    ports:
      - 8081:8081
    working_dir: /app

  hadoop-namenode:
    container_name: hadoop-namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=hadoop-cluster
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070

  hadoop-datanode-1:
    container_name: hadoop-datanode-1
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on: 
      - hadoop-namenode
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

  jupyter:
    container_name: jupyter
    build: 
      dockerfile: jupyter.dockerfile
    ports:
      - 8889:8889
    volumes:
      - ./notebooks:/notebooks
